project:
  type: website
  output-dir: docs
  
website:
  title: "Jeffrey W. Hollister"
  navbar:
    right:
      - about.qmd
      - cv.qmd
      - talks.qmd
      - icon: github
        href: https://github.com/jhollist

format:
  html:
    theme: spacelab
    css: styles.css



