project:
  type: website
  output-dir: docs
  
website:
  title: "jwhollister"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: spacelab
    css: styles.css



